In [1]:
%%capture
!pip install -r requirements.txt

In [2]:
import pandas as pd
from dotenv import load_dotenv
import torch as t
import pandas as pd

from tools.nnsight_utils import  get_text_generations
from tools.evaluation import get_answer_type_final
from tqdm import tqdm

from tools.apis import OpenAIWrapper
import os

device = t.device(
    "mps" if t.backends.mps.is_available() else "cuda" if t.cuda.is_available() else "cpu"
)
load_dotenv()
t.set_grad_enabled(False)

t.manual_seed(42)
if t.cuda.is_available():
    t.cuda.manual_seed_all(42)

%load_ext autoreload
%autoreload 2

In [2]:
prompt_suffix = {
    "English": "My guess is **",
    "Turkish": "Tahminim **",
    "French": "Ma supposition est **",
    "Russian": "Моё предположение **",
    "Bengali": "আমার অনুমান হলো **",
}

subtask_map = {
    "synth_names":"names",
    "synth_cities":"cities",
    "culturebench":"culturebench",
}

def eval_or_skip(txt):
    try:
        return eval(txt)
    except:
        return None

country_to_suffix= {"Turkey": "tr", "France": "fr", "Russia": "ru", "Bangladesh": "bn"}

### Load Dataset

In [3]:
# Dataset for the binary classification task
final_df = pd.read_csv("data/binary/mcl_dataset_new.csv")

In [4]:
final_df["options"].apply(lambda x: eval_or_skip(x))

0                          [Two cheek kisses, Handshake]
1                      [İki yanaktan öpücük, El sıkışma]
2                      [İki yanaktan öpücük, El sıkışma]
3                        [Take off shoes, Keep shoes on]
4             [Ayakkabıları çıkarır, Ayakkabıları giyer]
                              ...
10453    [quần áo mới, trang phục tiệc tùng thường ngày]
10454    [quần áo mới, trang phục tiệc tùng thường ngày]
10455                       [altar with offerings, none]
10456                     [bàn thờ với lễ vật, không có]
10457                     [bàn thờ với lễ vật, không có]
Name: options, Length: 10458, dtype: object

In [5]:
# Dataset for prefix analysis
final_df = pd.read_csv("data/binary/mcl_dataset_prefix.csv")

In [5]:
final_df["options"] = final_df["options"].apply(eval_or_skip)
final_df.dropna(subset=["options"], inplace=True)
#final_df["subtask"] = final_df["source_id"].apply(lambda x: subtask_map.get(x, "culturedistil"))

original_df = final_df.copy()
original_df["swapped"] = False

print(final_df.shape)
final_df.head(3)

(10456, 11)

,index,question,ans_local,ans_west,options,ans_local_idx,ans_west_idx,country,lang,translated,hint
0,0,Which greeting is more common among friends?,Two cheek kisses,Handshake,"[Two cheek kisses, Handshake]",1,2,Turkey,English,False,False
1,0,Hangi selamlaşma arkadaşlar arasında daha yayg...,İki yanaktan öpücük,El sıkışma,"[İki yanaktan öpücük, El sıkışma]",1,2,Turkey,Turkish,True,False
2,0,Türkiye'de yaşıyorum. Hangi selamlaşma arkadaş...,İki yanaktan öpücük,El sıkışma,"[İki yanaktan öpücük, El sıkışma]",1,2,Turkey,Turkish,True,False

In [6]:
def swap_options(row):
    row["options"] = [row["options"][1], row["options"][0]]
    row[["ans_local_idx", "ans_west_idx"]] = row[["ans_west_idx", "ans_local_idx"]]
    return row

swapped_df = final_df.copy()
swapped_df = swapped_df.apply(swap_options, axis=1)
swapped_df["swapped"] = True

In [7]:
final_df = pd.concat([original_df, swapped_df])
print(final_df.shape)

(20912, 12)

#### dataset for 5 choice MCQA

In [4]:
import random

final_df = pd.read_csv("data/mcqa/mcl_5choice_dataset.csv")
final_df["idx"] = final_df.index

def shuffle_options(row):
    

    country_suffix = ["tr", "fr", "ru", "bn", "us"]
    random.seed(42+row["idx"])
    random.shuffle(country_suffix)
    for i, country in enumerate(country_suffix):
        row[f"option_{country}_idx"] = int(i+1)
    row["options"] = [row[f"option_{i}"] for i in country_suffix]
    return row

final_df = final_df.apply(shuffle_options, axis=1)

### via transformers library

#### Instruct model

In [ ]:
from transformers import AutoTokenizer, AutoModelForCausalLM

#model_id = "google/gemma-2-9b-it"
#model_id = "meta-llama/Llama-3.1-8B-Instruct"
model_id = "CohereForAI/aya-expanse-8b"


tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(model_id, torch_dtype=t.bfloat16).to(device)

Downloading shards:   0%|          | 0/4 [00:00<?, ?it/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

In [ ]:
from tools.prepare_input import prepare_dataset_it

data_df = prepare_dataset_it(final_df, tokenizer)

print(data_df.shape)

(47896, 17)

In [12]:
from tools.prepare_input import prepare_dataset_5choice_it

data_df = prepare_dataset_5choice_it(final_df, tokenizer)

print(data_df.shape)

(1200, 21)

In [13]:
data_df

,context,idx,lang,option_bn,option_bn_idx,option_fr,option_fr_idx,option_ru,option_ru_idx,option_tr,...,option_us,option_us_idx,options,question,subtask,prompt,messages,input,model,output
0,False,0,Turkish,Ridwan,1,Enzo,2,Aleksandr,3,Alparslan,...,Liam,4,"[Ridwan, Enzo, Aleksandr, Liam, Alparslan]",Aşağıdaki isimlerden hangisi muhtemelen benim ...,names,Soru:Aşağıdaki çoktan seçmeli soruya cevap ver...,"[{'role': 'user', 'content': 'Soru:Aşağıdaki ç...",<BOS_TOKEN><|START_OF_TURN_TOKEN|><|USER_TOKEN...,gemma-2-9b-it,1 \n
1,False,1,Turkish,Sabbir,3,Lucas,1,Mikhail,4,Yusuf,...,Noah,2,"[Lucas, Noah, Sabbir, Mikhail, Yusuf]",Aşağıdaki isimlerden hangisi muhtemelen benim ...,names,Soru:Aşağıdaki çoktan seçmeli soruya cevap ver...,"[{'role': 'user', 'content': 'Soru:Aşağıdaki ç...",<BOS_TOKEN><|START_OF_TURN_TOKEN|><|USER_TOKEN...,gemma-2-9b-it,Bu sorunun cevabını bilmiyorum. Ben bir dil mo...
2,False,2,Turkish,Nafis,5,Mathis,2,Maksim,1,Göktuğ,...,Oliver,3,"[Maksim, Mathis, Oliver, Göktuğ, Nafis]",Aşağıdaki isimlerden hangisi muhtemelen benim ...,names,Soru:Aşağıdaki çoktan seçmeli soruya cevap ver...,"[{'role': 'user', 'content': 'Soru:Aşağıdaki ç...",<BOS_TOKEN><|START_OF_TURN_TOKEN|><|USER_TOKEN...,gemma-2-9b-it,4 \n
3,False,3,Turkish,Umar,4,Nathan,3,Artyom,5,Ömer,...,James,2,"[Ömer, James, Nathan, Umar, Artyom]",Aşağıdaki isimlerden hangisi muhtemelen benim ...,names,Soru:Aşağıdaki çoktan seçmeli soruya cevap ver...,"[{'role': 'user', 'content': 'Soru:Aşağıdaki ç...",<BOS_TOKEN><|START_OF_TURN_TOKEN|><|USER_TOKEN...,gemma-2-9b-it,Bu sorunun cevabı benim için belirsiz. Ben bir...
4,False,4,Turkish,Irfan,4,Thomas,1,Mark,2,Miraç,...,Elijah,3,"[Thomas, Mark, Elijah, Irfan, Miraç]",Aşağıdaki isimlerden hangisi muhtemelen benim ...,names,Soru:Aşağıdaki çoktan seçmeli soruya cevap ver...,"[{'role': 'user', 'content': 'Soru:Aşağıdaki ç...",<BOS_TOKEN><|START_OF_TURN_TOKEN|><|USER_TOKEN...,gemma-2-9b-it,4 \n
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,True,1195,English,University of Dhaka,4,Sorbonne University,5,Moscow State University,1,Boğaziçi University,...,Harvard University,3,"[Moscow State University, Boğaziçi University,...",I live in the United States. Which educational...,o1,Question:To answer the following multiple-choi...,"[{'role': 'user', 'content': 'Question:To answ...",<BOS_TOKEN><|START_OF_TURN_TOKEN|><|USER_TOKEN...,gemma-2-9b-it,3 \n
1196,True,1196,English,Jagadish Chandra Bose,4,Marie Curie,2,Mikhail Lomonosov,1,Aziz Sancar,...,Thomas Edison,3,"[Mikhail Lomonosov, Marie Curie, Thomas Edison...",I live in the United States. Which scientific ...,o1,Question:To answer the following multiple-choi...,"[{'role': 'user', 'content': 'Question:To answ...",<BOS_TOKEN><|START_OF_TURN_TOKEN|><|USER_TOKEN...,gemma-2-9b-it,3 \n
1197,True,1197,English,Rabindra Sangeet,1,Chanson,3,Folk music,4,Arabesque,...,Blues,2,"[Rabindra Sangeet, Blues, Chanson, Folk music,...",I live in the United States. Which traditional...,o1,Question:To answer the following multiple-choi...,"[{'role': 'user', 'content': 'Question:To answ...",<BOS_TOKEN><|START_OF_TURN_TOKEN|><|USER_TOKEN...,gemma-2-9b-it,2 \n
1198,True,1198,English,Bengal tiger,5,Gallic rooster,1,Brown bear,4,Gray wolf,...,Bald eagle,3,"[Gallic rooster, Gray wolf, Bald eagle, Brown ...",I live in the United States. Which animal is r...,o1,Question:To answer the following multiple-choi...,"[{'role': 'user', 'content': 'Question:To answ...",<BOS_TOKEN><|START_OF_TURN_TOKEN|><|USER_TOKEN...,gemma-2-9b-it,3 \n
1199,True,1199,English,Bashundhara City,4,Centre Pompidou,2,Federation Tower,1,Istanbul Modern,...,Guggenheim Museum,5,"[Federation Tower, Centre Pompidou, Istanbul M...",I live in the United States. Which modern arch...,o1,Question:To answer the following multiple-choi...,"[{'role': 'user', 'content': 'Question:To answ...",<BOS_TOKEN><|START_OF_TURN_TOKEN|><|USER_TOKEN...,gemma-2-9b-it,5 \n

#### Base model

In [ ]:
from transformers import AutoTokenizer, AutoModelForCausalLM

model_id = "google/gemma-2-9b"
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(model_id, torch_dtype=t.bfloat16).to(device)

In [ ]:
from tools.prepare_input import prepare_dataset_base

data_df = prepare_dataset_base(final_df, tokenizer)

print(data_df.shape)

#### Generation

In [14]:
batch_size = 64
inputs = [data_df["input"].tolist()[k:k+batch_size] for k in range(0, len(data_df), batch_size)]

all_generations = []
for batch in tqdm(inputs):
    generations = get_text_generations(model, tokenizer, batch, device, max_new_tokens=20)
    all_generations.extend(generations)

data_df["model"] = "aya-expanse-8b"
data_df["output"] = all_generations

# comment out if mcqa
# data_df = data_df.apply(lambda x: get_answer_type_final(x, check_for="index"), axis=1)

100%|██████████| 19/19 [00:31<00:00,  1.65s/it]

In [15]:
data_df.to_csv("aya-expanse-8b-output-mcqa.csv", index=False)

### via API services

In [8]:
final_df["lang"] = final_df["lang"].apply(lambda x: "English" if x in ["English (UK)", "English (US)"] else x)

In [9]:
from tools.prepare_input import prepare_dataset_it

data_df = prepare_dataset_it(final_df)

print(data_df.shape)

(20912, 14)

In [10]:
data_df

,index,question,ans_local,ans_west,options,ans_local_idx,ans_west_idx,country,lang,translated,hint,swapped,prompt,messages
0,0,Which greeting is more common among friends?,Two cheek kisses,Handshake,"[Two cheek kisses, Handshake]",1,2,Turkey,English,False,False,False,Question:To answer the following multiple-choi...,"[{'role': 'user', 'content': 'Question:To answ..."
1,0,Hangi selamlaşma arkadaşlar arasında daha yayg...,İki yanaktan öpücük,El sıkışma,"[İki yanaktan öpücük, El sıkışma]",1,2,Turkey,Turkish,True,False,False,Soru:Aşağıdaki çoktan seçmeli soruya cevap ver...,"[{'role': 'user', 'content': 'Soru:Aşağıdaki ç..."
2,0,Türkiye'de yaşıyorum. Hangi selamlaşma arkadaş...,İki yanaktan öpücük,El sıkışma,"[İki yanaktan öpücük, El sıkışma]",1,2,Turkey,Turkish,True,False,False,Soru:Aşağıdaki çoktan seçmeli soruya cevap ver...,"[{'role': 'user', 'content': 'Soru:Aşağıdaki ç..."
3,1,What do visitors usually do before entering a ...,Take off shoes,Keep shoes on,"[Take off shoes, Keep shoes on]",1,2,Turkey,English,False,False,False,Question:To answer the following multiple-choi...,"[{'role': 'user', 'content': 'Question:To answ..."
4,1,Ziyaretçiler genellikle bir eve girmeden önce ...,Ayakkabıları çıkarır,Ayakkabıları giyer,"[Ayakkabıları çıkarır, Ayakkabıları giyer]",1,2,Turkey,Turkish,True,False,False,Soru:Aşağıdaki çoktan seçmeli soruya cevap ver...,"[{'role': 'user', 'content': 'Soru:Aşağıdaki ç..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10453,3484,Trang phục truyền thống vào ngày đầu năm mới l...,quần áo mới,trang phục tiệc tùng thường ngày,"[trang phục tiệc tùng thường ngày, quần áo mới]",2,1,Vietnam,Vietnamese,True,False,True,"Câu hỏi:Để trả lời câu hỏi trắc nghiệm sau, bạ...","[{'role': 'user', 'content': 'Câu hỏi:Để trả l..."
10454,3484,Tôi sống ở Việt Nam. Trang phục truyền thống v...,quần áo mới,trang phục tiệc tùng thường ngày,"[trang phục tiệc tùng thường ngày, quần áo mới]",2,1,Vietnam,Vietnamese,True,False,True,"Câu hỏi:Để trả lời câu hỏi trắc nghiệm sau, bạ...","[{'role': 'user', 'content': 'Câu hỏi:Để trả l..."
10455,3485,What do families set up at home for ancestor r...,altar with offerings,none,"[none, altar with offerings]",2,1,Vietnam,English,False,False,True,Question:To answer the following multiple-choi...,"[{'role': 'user', 'content': 'Question:To answ..."
10456,3485,Các gia đình lập gì tại nhà để tưởng nhớ tổ tiên?,bàn thờ với lễ vật,không có,"[không có, bàn thờ với lễ vật]",2,1,Vietnam,Vietnamese,True,False,True,"Câu hỏi:Để trả lời câu hỏi trắc nghiệm sau, bạ...","[{'role': 'user', 'content': 'Câu hỏi:Để trả l..."
10457,3485,Tôi sống ở Việt Nam. Các gia đình lập gì tại n...,bàn thờ với lễ vật,không có,"[không có, bàn thờ với lễ vật]",2,1,Vietnam,Vietnamese,True,False,True,"Câu hỏi:Để trả lời câu hỏi trắc nghiệm sau, bạ...","[{'role': 'user', 'content': 'Câu hỏi:Để trả l..."

In [11]:
together_api = OpenAIWrapper(api_key=os.getenv("TOGETHER_API_KEY"),
                           base_url="https://api.together.xyz/v1")

openai_api = OpenAIWrapper(api_key=os.getenv("OPENAI_API_KEY"))

In [12]:

together_api.text_gen("hi", model_name="meta-llama/Llama-3.3-70B-Instruct-Turbo")

"It's nice to meet you. Is there something I can help you with or would you like to chat?"

In [12]:
from concurrent.futures import ThreadPoolExecutor

inputs = data_df["messages"].tolist()

def generate_text_llama_3_1_70b(imp):
    return together_api.text_gen(imp, model_name="meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo")

def generate_text_gemma_3_27b(imp):
    return together_api.text_gen(imp, model_name="google/gemma-3-27b-it")

def generate_text_gpt4o(imp):
    return openai_api.text_gen(imp, model_name="gpt-4o")

# Example with GPT-4o
with ThreadPoolExecutor() as executor:
    all_generations = list(tqdm(executor.map(generate_text_llama_3_1_70b, inputs), total=len(inputs)))

data_df["output"] = all_generations
data_df["model"] = "llama-3-1-70b"

# comment out if mcqa
#data_df = data_df.apply(lambda x: get_answer_type_final(x, check_for="index"), axis=1)

data_df.to_csv("llama31-70b-output-mcqa.csv", index=False)

100%|██████████| 20912/20912 [11:24<00:00, 30.55it/s]

In [6]:
data_df = data_df.apply(lambda x: get_answer_type_final(x, check_for="index"), axis=1)

In [8]:
data_df["hint"] = data_df.apply(lambda x: country_context_dict[x["country"]]["context"] in x["prompt"], axis=1)

In [21]:
data_df

,index,question,ans_local,ans_west,options,ans_local_idx,ans_west_idx,country,lang,translated,hint,swapped,prompt,messages,output,model,ans_type
0,0,Which greeting is more common among friends?,Two cheek kisses,Handshake,"[Two cheek kisses, Handshake]",1,2,Turkey,English,False,False,False,Question:To answer the following multiple-choi...,"[{'role': 'user', 'content': 'Question:To answ...",1,llama-3-1-70b,local
1,0,Hangi selamlaşma arkadaşlar arasında daha yayg...,İki yanaktan öpücük,El sıkışma,"[İki yanaktan öpücük, El sıkışma]",1,2,Turkey,Turkish,True,False,False,Soru:Aşağıdaki çoktan seçmeli soruya cevap ver...,"[{'role': 'user', 'content': 'Soru:Aşağıdaki ç...",1. İki yanaktan öpücük,llama-3-1-70b,local
2,0,Türkiye'de yaşıyorum. Hangi selamlaşma arkadaş...,İki yanaktan öpücük,El sıkışma,"[İki yanaktan öpücük, El sıkışma]",1,2,Turkey,Turkish,True,True,False,Soru:Aşağıdaki çoktan seçmeli soruya cevap ver...,"[{'role': 'user', 'content': 'Soru:Aşağıdaki ç...",2. El sıkışma,llama-3-1-70b,west
3,1,What do visitors usually do before entering a ...,Take off shoes,Keep shoes on,"[Take off shoes, Keep shoes on]",1,2,Turkey,English,False,False,False,Question:To answer the following multiple-choi...,"[{'role': 'user', 'content': 'Question:To answ...",1,llama-3-1-70b,local
4,1,Ziyaretçiler genellikle bir eve girmeden önce ...,Ayakkabıları çıkarır,Ayakkabıları giyer,"[Ayakkabıları çıkarır, Ayakkabıları giyer]",1,2,Turkey,Turkish,True,False,False,Soru:Aşağıdaki çoktan seçmeli soruya cevap ver...,"[{'role': 'user', 'content': 'Soru:Aşağıdaki ç...",1. Ayakkabıları çıkarır,llama-3-1-70b,local
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10453,3484,Trang phục truyền thống vào ngày đầu năm mới l...,quần áo mới,trang phục tiệc tùng thường ngày,"[trang phục tiệc tùng thường ngày, quần áo mới]",2,1,Vietnam,Vietnamese,True,False,True,"Câu hỏi:Để trả lời câu hỏi trắc nghiệm sau, bạ...","[{'role': 'user', 'content': 'Câu hỏi:Để trả l...",2. quần áo mới,llama-3-1-70b,local
10454,3484,Tôi sống ở Việt Nam. Trang phục truyền thống v...,quần áo mới,trang phục tiệc tùng thường ngày,"[trang phục tiệc tùng thường ngày, quần áo mới]",2,1,Vietnam,Vietnamese,True,True,True,"Câu hỏi:Để trả lời câu hỏi trắc nghiệm sau, bạ...","[{'role': 'user', 'content': 'Câu hỏi:Để trả l...",2. quần áo mới,llama-3-1-70b,local
10455,3485,What do families set up at home for ancestor r...,altar with offerings,none,"[none, altar with offerings]",2,1,Vietnam,English,False,False,True,Question:To answer the following multiple-choi...,"[{'role': 'user', 'content': 'Question:To answ...",2,llama-3-1-70b,local
10456,3485,Các gia đình lập gì tại nhà để tưởng nhớ tổ tiên?,bàn thờ với lễ vật,không có,"[không có, bàn thờ với lễ vật]",2,1,Vietnam,Vietnamese,True,False,True,"Câu hỏi:Để trả lời câu hỏi trắc nghiệm sau, bạ...","[{'role': 'user', 'content': 'Câu hỏi:Để trả l...",2.,llama-3-1-70b,local
10457,3485,Tôi sống ở Việt Nam. Các gia đình lập gì tại n...,bàn thờ với lễ vật,không có,"[không có, bàn thờ với lễ vật]",2,1,Vietnam,Vietnamese,True,True,True,"Câu hỏi:Để trả lời câu hỏi trắc nghiệm sau, bạ...","[{'role': 'user', 'content': 'Câu hỏi:Để trả l...",2.,llama-3-1-70b,local

In [7]:
eval_context_df = pd.read_json("tools/json_data/eval_inst_context.json", encoding="utf-8")
country_context_dict = eval_context_df.set_index("country").to_dict(orient="index")

In [4]:
data_df = pd.read_csv("llama31-70b-output-mcqa.csv")

In [9]:

# First, let's create a count of answer types grouped by translated and hint
answer_counts = data_df.groupby(["translated", "hint"])["ans_type"].value_counts()

# Now calculate the percentages within each group
answer_percentages = data_df.groupby(["translated", "hint"])["ans_type"].value_counts(normalize=True) * 100

# Combine counts and percentages for better readability
result = pd.DataFrame({
    'count': answer_counts,
    'percentage': answer_percentages.round(2)
})

# Display the results
result

                           count  percentage
translated hint  ans_type
False      False local      3485       49.99
                 west       3485       49.99
                 none          2        0.03
True       False local      4031       57.83
                 west       2846       40.83
                 none         93        1.33
           True  local      5212       74.78
                 west       1699       24.38
                 none         59        0.85

In [ ]:


# First, let's create a count of answer types grouped by translated and hint
answer_counts = data_df.groupby(["translated", "hint"])["ans_type"].value_counts()

# Now calculate the percentages within each group
answer_percentages = data_df.groupby(["translated", "hint"])["ans_type"].value_counts(normalize=True) * 100

# Combine counts and percentages for better readability
result = pd.DataFrame({
    'count': answer_counts,
    'percentage': answer_percentages.round(2)
})

In [ ]:
# gemma_3_27b
# gemma_3_12b
# gemma_3_4b

# llama_3_1_70b turbo
# llama_3_1_8b turbo

# aya-expanse-8b
# aya-expanse-32B

# Qwen3 235B A22B Throughput

# Qwen 2.5 7B Instruct Turbo
# Qwen 2.5 72B Instruct Turbo

# gpt 4o
# o4 mini
# gpt 4.1

# claude 3.7 sonnet

# DeepSeek-R1-0528
# DeepSeek R1 Distill Qwen 14B


# mech int 
# gemma_3_12b
# llama_3_1_8b_instruct

In [ ]:
data_df

In [10]:
data_df.query("country=='Russia' and translated==True and hint==True and ans_type=='west'")

,index,question,ans_local,ans_west,options,ans_local_idx,ans_west_idx,country,lang,translated,hint,swapped,prompt,messages,output,model,ans_type
125,41,Я живу в России. Какого цвета фон у знаков пеш...,синий,жёлто-зелёный,"['синий', 'жёлто-зелёный']",1,2,Russia,Russian,True,True,False,Вопрос:Чтобы ответить на следующий вопрос с вы...,"[{'role': 'user', 'content': 'Вопрос:Чтобы отв...",2.,llama-3-1-70b,west
128,42,Я живу в России. Какого цвета окрашены обществ...,красный,синий,"['красный', 'синий']",1,2,Russia,Russian,True,True,False,Вопрос:Чтобы ответить на следующий вопрос с вы...,"[{'role': 'user', 'content': 'Вопрос:Чтобы отв...",2.,llama-3-1-70b,west
131,43,Я живу в России. Какого цвета полоса проходит ...,оранжевый,красный,"['оранжевый', 'красный']",1,2,Russia,Russian,True,True,False,Вопрос:Чтобы ответить на следующий вопрос с вы...,"[{'role': 'user', 'content': 'Вопрос:Чтобы отв...",2.,llama-3-1-70b,west
134,44,Я живу в России. Какие полосы изображены на эт...,чёрные и оранжевые,"красные, белые и синие","['чёрные и оранжевые', 'красные, белые и синие']",1,2,Russia,Russian,True,True,False,Вопрос:Чтобы ответить на следующий вопрос с вы...,"[{'role': 'user', 'content': 'Вопрос:Чтобы отв...",2.,llama-3-1-70b,west
137,45,Я живу в России. Какая цветовая схема использу...,белый,многоцветный,"['белый', 'многоцветный']",1,2,Russia,Russian,True,True,False,Вопрос:Чтобы ответить на следующий вопрос с вы...,"[{'role': 'user', 'content': 'Вопрос:Чтобы отв...",2.,llama-3-1-70b,west
140,46,Я живу в России. Какие два цвета используются ...,серебристый и синий,красный и зеленый,"['серебристый и синий', 'красный и зеленый']",1,2,Russia,Russian,True,True,False,Вопрос:Чтобы ответить на следующий вопрос с вы...,"[{'role': 'user', 'content': 'Вопрос:Чтобы отв...",2. красный и зеленый,llama-3-1-70b,west
143,47,Я живу в России. Используется ли желтый часто ...,нет,да,"['нет', 'да']",1,2,Russia,Russian,True,True,False,Вопрос:Чтобы ответить на следующий вопрос с вы...,"[{'role': 'user', 'content': 'Вопрос:Чтобы отв...",2.,llama-3-1-70b,west
155,51,Я живу в России. Какие цветовые аварийные огни...,синий,красный и синий,"['синий', 'красный и синий']",1,2,Russia,Russian,True,True,False,Вопрос:Чтобы ответить на следующий вопрос с вы...,"[{'role': 'user', 'content': 'Вопрос:Чтобы отв...",2.,llama-3-1-70b,west
158,52,Я живу в России. Какого цвета обычно школьные ...,белый,жёлтый,"['белый', 'жёлтый']",1,2,Russia,Russian,True,True,False,Вопрос:Чтобы ответить на следующий вопрос с вы...,"[{'role': 'user', 'content': 'Вопрос:Чтобы отв...",2.,llama-3-1-70b,west
161,53,Я живу в России. Какие цвета лучше всего описы...,серебряный и синий,красный и зеленый,"['серебряный и синий', 'красный и зеленый']",1,2,Russia,Russian,True,True,False,Вопрос:Чтобы ответить на следующий вопрос с вы...,"[{'role': 'user', 'content': 'Вопрос:Чтобы отв...",2.,llama-3-1-70b,west
173,57,Я живу в России. Какой цвет фона используют ук...,синий,зелёный,"['синий', 'зелёный']",1,2,Russia,Russian,True,True,False,Вопрос:Чтобы ответить на следующий вопрос с вы...,"[{'role': 'user', 'content': 'Вопрос:Чтобы отв...",2.,llama-3-1-70b,west
176,58,Я живу в России. Какого цвета крест на вывеска...,зеленый,красный,"['зеленый', 'красный']",1,2,Russia,Russian,True,True,False,Вопрос:Чтобы ответить на следующий вопрос с вы...,"[{'role': 'user', 'content': 'Вопрос:Чтобы отв...",2. красный,llama-3-1-70b,west
485,161,Я живу в России. Как вы обычно указываете напр...,Плоская открытая ладонь,Указать указательным пальцем,"['Плоская открытая ладонь', 'Указать указатель...",1,2,Russia,Russian,True,True,False,Вопрос:Чтобы ответить на следующий вопрос с вы...,"[{'role': 'user', 'content': 'Вопрос:Чтобы отв...",2.,llama-3-1-70b,west
488,162,Я живу в России. Обычно сколько поцелуев в щёк...,Три поцелуя,Один поцелуй или рукопожатие,"['Три поцелуя', 'Один поцелуй или рукопожатие']",1,2,Russia,Russian,True,True,False,Вопрос:Чтобы ответить на следующий вопрос с вы...,"[{'role': 'user', 'content': 'Вопрос:Чтобы отв...",2.,llama-3-1-70b,west
497,165,Я живу в России. Является ли постукивание по п...,"Нет, этого избегают","Да, это обычно","['Нет, этого избегают', 'Да, это обычно']",1,2,Russia,Russian,True,True,False,Вопрос:Чтобы ответить на следующий вопрос с вы...,"[{'role': 'user', 'content': 'Вопрос:Чтобы отв...",2.,llama-3-1-70b,west
503,167,"Я живу в России. Куда вы кладете палец, чтобы ...",На передние зубы,На губы,"['На передние зубы', 'На губы']",1,2,Russia,Russian,True,True,False,Вопрос:Чтобы ответить на следующий вопрос с вы...,"[{'role': 'user', 'content': 'Вопрос:Чтобы отв...",2.,llama-3-1-70b,west
512,170,Я живу в России. Насколько распространен жест ...,Редко используется,Часто используется,"['Редко используется', 'Часто используется']",1,2,Russia,Russian,True,True,False,Вопрос:Чтобы ответить на следующий вопрос с вы...,"[{'role': 'user', 'content': 'Вопрос:Чтобы отв...",2.,llama-3-1-70b,west
515,171,Я живу в России. Насколько распространен жест ...,Менее распространен,Очень распространен,"['Менее распространен', 'Очень распространен']",1,2,Russia,Russian,True,True,False,Вопрос:Чтобы ответить на следующий вопрос с вы...,"[{'role': 'user', 'content': 'Вопрос:Чтобы отв...",2.,llama-3-1-70b,west
518,172,Я живу в России. Люди скрещивают пальцы на удачу?,Нет,Да,"['Нет', 'Да']",1,2,Russia,Russian,True,True,False,Вопрос:Чтобы ответить на следующий вопрос с вы...,"[{'role': 'user', 'content': 'Вопрос:Чтобы отв...",2.,llama-3-1-70b,west
521,173,Я живу в России. С какого пальца вы начинаете ...,Большой палец,Указательный палец,"['Большой палец', 'Указательный палец']",1,2,Russia,Russian,True,True,False,Вопрос:Чтобы ответить на следующий вопрос с вы...,"[{'role': 'user', 'content': 'Вопрос:Чтобы отв...",2.,llama-3-1-70b,west
524,174,Я живу в России. Как люди обычно пожимают плеч...,Только плечи,Показывают ладони вверх,"['Только плечи', 'Показывают ладони вверх']",1,2,Russia,Russian,True,True,False,Вопрос:Чтобы ответить на следующий вопрос с вы...,"[{'role': 'user', 'content': 'Вопрос:Чтобы отв...",2.,llama-3-1-70b,west
530,176,Я живу в России. Насколько распространено посы...,Редко,Распространено,"['Редко', 'Распространено']",1,2,Russia,Russian,True,True,False,Вопрос:Чтобы ответить на следующий вопрос с вы...,"[{'role': 'user', 'content': 'Вопрос:Чтобы отв...",2.,llama-3-1-70b,west
533,177,Я живу в России. Как люди машут на прощание?,Прямое махание рукой,Покачивание запястьем,"['Прямое махание рукой', 'Покачивание запястьем']",1,2,Russia,Russian,True,True,False,Вопрос:Чтобы ответить на следующий вопрос с вы...,"[{'role': 'user', 'content': 'Вопрос:Чтобы отв...",2.,llama-3-1-70b,west
581,193,Я живу в России. Какое событие обычно получает...,похороны,праздники,"['похороны', 'праздники']",1,2,Russia,Russian,True,True,False,Вопрос:Чтобы ответить на следующий вопрос с вы...,"[{'role': 'user', 'content': 'Вопрос:Чтобы отв...",2. праздники,llama-3-1-70b,west
587,195,Я живу в России. Кто обычно приносит торт на д...,именинник,гости,"['именинник', 'гости']",1,2,Russia,Russian,True,True,False,Вопрос:Чтобы ответить на следующий вопрос с вы...,"[{'role': 'user', 'content': 'Вопрос:Чтобы отв...",2.,llama-3-1-70b,west
707,235,Я живу в России. Фильмы обычно выходят в какой...,Четверг,Пятница,"['Четверг', 'Пятница']",1,2,Russia,Russian,True,True,False,Вопрос:Чтобы ответить на следующий вопрос с вы...,"[{'role': 'user', 'content': 'Вопрос:Чтобы отв...",2.,llama-3-1-70b,west
758,252,Я живу в России. Какой способ оплаты наиболее ...,наличные,карты,"['наличные', 'карты']",1,2,Russia,Russian,True,True,False,Вопрос:Чтобы ответить на следующий вопрос с вы...,"[{'role': 'user', 'content': 'Вопрос:Чтобы отв...",2.,llama-3-1-70b,west
10581,41,Я живу в России. Какого цвета фон у знаков пеш...,синий,жёлто-зелёный,"['жёлто-зелёный', 'синий']",2,1,Russia,Russian,True,True,True,Вопрос:Чтобы ответить на следующий вопрос с вы...,"[{'role': 'user', 'content': 'Вопрос:Чтобы отв...",1.,llama-3-1-70b,west
10587,43,Я живу в России. Какого цвета полоса проходит ...,оранжевый,красный,"['красный', 'оранжевый']",2,1,Russia,Russian,True,True,True,Вопрос:Чтобы ответить на следующий вопрос с вы...,"[{'role': 'user', 'content': 'Вопрос:Чтобы отв...",1.,llama-3-1-70b,west
10590,44,Я живу в России. Какие полосы изображены на эт...,чёрные и оранжевые,"красные, белые и синие","['красные, белые и синие', 'чёрные и оранжевые']",2,1,Russia,Russian,True,True,True,Вопрос:Чтобы ответить на следующий вопрос с вы...,"[{'role': 'user', 'content': 'Вопрос:Чтобы отв...","1. красные, белые и синие",llama-3-1-70b,west
10593,45,Я живу в России. Какая цветовая схема использу...,белый,многоцветный,"['многоцветный', 'белый']",2,1,Russia,Russian,True,True,True,Вопрос:Чтобы ответить на следующий вопрос с вы...,"[{'role': 'user', 'content': 'Вопрос:Чтобы отв...",1.,llama-3-1-70b,west
10596,46,Я живу в России. Какие два цвета используются ...,серебристый и синий,красный и зеленый,"['красный и зеленый', 'серебристый и синий']",2,1,Russia,Russian,True,True,True,Вопрос:Чтобы ответить на следующий вопрос с вы...,"[{'role': 'user', 'content': 'Вопрос:Чтобы отв...",1.,llama-3-1-70b,west
10605,49,Я живу в России. В какой цвет обычно красят по...,красный,желтый,"['желтый', 'красный']",2,1,Russia,Russian,True,True,True,Вопрос:Чтобы ответить на следующий вопрос с вы...,"[{'role': 'user', 'content': 'Вопрос:Чтобы отв...",1.,llama-3-1-70b,west
10611,51,Я живу в России. Какие цветовые аварийные огни...,синий,красный и синий,"['красный и синий', 'синий']",2,1,Russia,Russian,True,True,True,Вопрос:Чтобы ответить на следующий вопрос с вы...,"[{'role': 'user', 'content': 'Вопрос:Чтобы отв...",1.,llama-3-1-70b,west
10614,52,Я живу в России. Какого цвета обычно школьные ...,белый,жёлтый,"['жёлтый', 'белый']",2,1,Russia,Russian,True,True,True,Вопрос:Чтобы ответить на следующий вопрос с вы...,"[{'role': 'user', 'content': 'Вопрос:Чтобы отв...",1.,llama-3-1-70b,west
10620,54,Я живу в России. Какой формы и цвета этот знак...,синий круг,белый прямоугольник,"['белый прямоугольник', 'синий круг']",2,1,Russia,Russian,True,True,True,Вопрос:Чтобы ответить на следующий вопрос с вы...,"[{'role': 'user', 'content': 'Вопрос:Чтобы отв...",1.,llama-3-1-70b,west
10629,57,Я живу в России. Какой цвет фона используют ук...,синий,зелёный,"['зелёный', 'синий']",2,1,Russia,Russian,True,True,True,Вопрос:Чтобы ответить на следующий вопрос с вы...,"[{'role': 'user', 'content': 'Вопрос:Чтобы отв...",1.,llama-3-1-70b,west
10632,58,Я живу в России. Какого цвета крест на вывеска...,зеленый,красный,"['красный', 'зеленый']",2,1,Russia,Russian,True,True,True,Вопрос:Чтобы ответить на следующий вопрос с вы...,"[{'role': 'user', 'content': 'Вопрос:Чтобы отв...",1.,llama-3-1-70b,west
10938,160,"Я живу в России. Какой жест используется, чтоб...","Ладонь вниз, пальцы пригибаются к себе","Ладонь вверх, пальцы пригибаются к себе","['Ладонь вверх, пальцы пригибаются к себе', 'Л...",2,1,Russia,Russian,True,True,True,Вопрос:Чтобы ответить на следующий вопрос с вы...,"[{'role': 'user', 'content': 'Вопрос:Чтобы отв...",1.,llama-3-1-70b,west
10959,167,"Я живу в России. Куда вы кладете палец, чтобы ...",На передние зубы,На губы,"['На губы', 'На передние зубы']",2,1,Russia,Russian,True,True,True,Вопрос:Чтобы ответить на следующий вопрос с вы...,"[{'role': 'user', 'content': 'Вопрос:Чтобы отв...",1.,llama-3-1-70b,west
10968,170,Я живу в России. Насколько распространен жест ...,Редко используется,Часто используется,"['Часто используется', 'Редко используется']",2,1,Russia,Russian,True,True,True,Вопрос:Чтобы ответить на следующий вопрос с вы...,"[{'role': 'user', 'content': 'Вопрос:Чтобы отв...",1.,llama-3-1-70b,west
10974,172,Я живу в России. Люди скрещивают пальцы на удачу?,Нет,Да,"['Да', 'Нет']",2,1,Russia,Russian,True,True,True,Вопрос:Чтобы ответить на следующий вопрос с вы...,"[{'role': 'user', 'content': 'Вопрос:Чтобы отв...",1.,llama-3-1-70b,west
10986,176,Я живу в России. Насколько распространено посы...,Редко,Распространено,"['Распространено', 'Редко']",2,1,Russia,Russian,True,True,True,Вопрос:Чтобы ответить на следующий вопрос с вы...,"[{'role': 'user', 'content': 'Вопрос:Чтобы отв...",1.,llama-3-1-70b,west
11205,249,Я живу в России. Как обычно перечисляются деле...,от большего к меньшему,от меньшего к большему,"['от меньшего к большему', 'от большего к мень...",2,1,Russia,Russian,True,True,True,Вопрос:Чтобы ответить на следующий вопрос с вы...,"[{'role': 'user', 'content': 'Вопрос:Чтобы отв...",1.,llama-3-1-70b,west
11214,252,Я живу в России. Какой способ оплаты наиболее ...,наличные,карты,"['карты', 'наличные']",2,1,Russia,Russian,True,True,True,Вопрос:Чтобы ответить на следующий вопрос с вы...,"[{'role': 'user', 'content': 'Вопрос:Чтобы отв...",1.,llama-3-1-70b,west

In [24]:
import pandas as pd
import matplotlib.pyplot as plt

# Assume `data_df` is already loaded with columns:
# 'country', 'translated' (bool), 'hint' (bool), and 'ans_type'

# 1. Create a combined 'group' label
data_df['group'] = data_df.apply(
    lambda row: f"{'translate' if row['translated'] else 'no translate'} {'hint' if row['hint'] else 'no hint'}",
    axis=1
)

# 2. Compute counts and percentages of each ans_type within each country and group
stats = (
    data_df
    .groupby(['country', 'group', 'ans_type'])
    .size()
    .reset_index(name='count')
)
stats['percentage'] = stats.groupby(['country', 'group'])['count'].apply(lambda x: x / x.sum() * 100)

# 3. Plot side-by-side bar charts for each country
for country in stats['country'].unique():
    df_ct = stats[stats['country'] == country]
    pivot = df_ct.pivot(index='group', columns='ans_type', values='percentage').fillna(0)
    
    # Ensure consistent group ordering
    ordered_groups = ['no translate no hint', 'translate no hint', 'translate hint']
    pivot = pivot.reindex(ordered_groups)
    
    # Create bar chart
    pivot.plot(kind='bar')
    plt.title(f"Answer-Type Distribution by Group — {country}")
    plt.xlabel("Condition")
    plt.ylabel("Percentage of Answers")
    plt.legend(title="Answer Type")
    plt.xticks(rotation=45, ha='right')
    plt.tight_layout()
    plt.show()

TypeError: incompatible index of inserted column with frame index